import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Foot } from "../component/Footer";
import Nav from "../component/Nav";
import { Navbar } from "../component/์Navbar";

const style: React.CSSProperties = { background: "#FFFFFF", padding: "30px" };
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function calendarv2Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <header className="bg-white shadow">
        <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900">
            Appointment
          </h1>
        </div>
      </header>
      {children}
      <Foot />
    </>
  );
}
