import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Foot } from "../component/Footer";
import Nav from "../component/Nav";

const style: React.CSSProperties = { background: "#FFFFFF", padding: "30px" };
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function calendarv2Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav />
      {children}
      <Foot />'
    </>
  );
}
